name: Flutter CI on MacOS

run-name: ${{ github.actor }} is testing out Flutter apps on MacOS.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        channel: 'main' # or: 'beta', 'dev', 'master' (or 'main')
        architecture: x64

    - run: flutter pub get

    - run: flutter test

    - run: flutter build ios --release --no-codesign