// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBupYLfrKR0yJZCtyGi8fd1V9drZot5Al8',
    appId: '1:276813621730:web:59ff1da5307144a3dfb1bb',
    messagingSenderId: '276813621730',
    projectId: 'fyp-project-ec958',
    authDomain: 'fyp-project-ec958.firebaseapp.com',
    storageBucket: 'fyp-project-ec958.appspot.com',
    measurementId: 'G-KG7STYDP2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf78K3-5M5f5tD6obz3pMvjSNJkBFRTNU',
    appId: '1:276813621730:android:d9f8342bee4ab770dfb1bb',
    messagingSenderId: '276813621730',
    projectId: 'fyp-project-ec958',
    storageBucket: 'fyp-project-ec958.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLJfDbPdte9VchkurWz4NHGdCu1Ghz0cc',
    appId: '1:276813621730:ios:f27cfbb4477e9328dfb1bb',
    messagingSenderId: '276813621730',
    projectId: 'fyp-project-ec958',
    storageBucket: 'fyp-project-ec958.appspot.com',
    iosBundleId: 'com.example.fypv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLJfDbPdte9VchkurWz4NHGdCu1Ghz0cc',
    appId: '1:276813621730:ios:7317b22e787de180dfb1bb',
    messagingSenderId: '276813621730',
    projectId: 'fyp-project-ec958',
    storageBucket: 'fyp-project-ec958.appspot.com',
    iosBundleId: 'com.example.fypv2.RunnerTests',
  );
}
