// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaT4QekFjStQceCqiNgRqu7tp0GHed_8Q',
    appId: '1:338087830843:web:f4e5a111b4cdfacf37031e',
    messagingSenderId: '338087830843',
    projectId: 'quotelens',
    authDomain: 'quotelens.firebaseapp.com',
    storageBucket: 'quotelens.appspot.com',
    measurementId: 'G-7MWE5LJP4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJRTVpmE2JRIu-85bROrkpvlKw2eo6SRw',
    appId: '1:338087830843:android:a256bac1d8cc0d9437031e',
    messagingSenderId: '338087830843',
    projectId: 'quotelens',
    storageBucket: 'quotelens.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjEgD_l1Z9BZARKMiK9re1ZO_4C3FYZGs',
    appId: '1:338087830843:ios:b76caf94b956d07437031e',
    messagingSenderId: '338087830843',
    projectId: 'quotelens',
    storageBucket: 'quotelens.appspot.com',
    androidClientId: '338087830843-tjmtba89c6f11208ftqsae39qi9cbgcq.apps.googleusercontent.com',
    iosClientId: '338087830843-9ia6c77lamqnrs196v2lhgh7lcld86ul.apps.googleusercontent.com',
    iosBundleId: 'com.example.fypv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjEgD_l1Z9BZARKMiK9re1ZO_4C3FYZGs',
    appId: '1:338087830843:ios:b7ec6bd20ca1825537031e',
    messagingSenderId: '338087830843',
    projectId: 'quotelens',
    storageBucket: 'quotelens.appspot.com',
    androidClientId: '338087830843-tjmtba89c6f11208ftqsae39qi9cbgcq.apps.googleusercontent.com',
    iosClientId: '338087830843-1g5npmnvmppp3b4v9hct9lcj62n64lhn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fypv2.RunnerTests',
  );
}
