name: Flutter CI Android Test

run-name: ${{ github.actor }} is testing out new git push on Android.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Fix flutter SDK folder permission
        run: git config --global --add safe.directory /tmp/flutter/--

      - uses: subosito/flutter-action@v2

      - run: flutter pub get

      - run: flutter test

      - run: flutter build apk

      - run: flutter build appbundle