name: Flutter CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.18.0-0.1.pre"
      - run: flutter pub get
      - run: flutter --version
      #- run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
  apple:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.18.0-0.1.pre"
          architecture: x64
      - run: flutter --version
      - run: flutter pub get
      #- run: flutter test
      - run: flutter build ios --release --no-codesign
