name: Flutter CI iOS Test

run-name: ${{ github.actor }} is testing out new git push on iOS.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Fix flutter SDK folder permission
      run: git config --global --add safe.directory /tmp/flutter/--

    - uses: subosito/flutter-action@v2.12.0
      with:
        channel: 'main' # or: 'beta', 'dev', 'master' (or 'main')
        architecture: x64

    - run: flutter pub get

    - run: flutter test

    - run: flutter build ios --release --no-codesign