name: Flutter CI Workflow

on:
  push:
    branches: [main]
    tags:
      - v*
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get latest tag
        id: get_tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: "3.16.0"
          architecture: x64
          channel: beta
      - run: flutter pub get
      - run: flutter --version
      #- run: flutter test
      - run: flutter build apk --release
      - run: flutter build appbundle

      - name: Create Artifact
        uses: actions/upload-artifact@v4
        with:
          name: QuoteLens-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
          --repo="$GITHUB_REPOSITORY" \
          --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
          --generate-notes

  apple:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          # flutter-version: "3.16.0"
          channel: "beta"
          architecture: x64
      - run: |
          git config --global --add safe.directory /opt/hostedtoolcache/flutter/${{ steps.flutter-action.outputs.CHANNEL }}-${{ steps.flutter-action.outputs.VERSION }}-${{ steps.flutter-action.outputs.ARCHITECTURE }}
          flutter --version
      - run: flutter pub get
      #- run: flutter test
      - run: flutter build ios --release --no-codesign
